version: 0.2
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 928808255181.dkr.ecr.us-east-1.amazonaws.com
phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - REPOSITORY_URI=928808255181.dkr.ecr.us-east-1.amazonaws.com/awsdevops
      - CONTAINER_NAME="backend-container"
      - IMAGE_TAG="latest"
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinition.json
artifacts:
    files: imagedefinition.json
